package Laundry;

import static com.sun.webkit.perf.WCFontPerfLogger.reset;
import java.awt.Desktop;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import koneksi.koneksiDB;
import net.proteanit.sql.DbUtils;

public class pembayaran extends javax.swing.JFrame {
    pelanggan plg = new pelanggan();
    Connection connect;
    PreparedStatement pst;
    ResultSet rs;
    Statement st;
    

    
    public pembayaran() {
        initComponents();
        connect=koneksiDB.getkoneksi();
        tampildatapesan();
        tampildataambil();
    }
    //Method tampil data pesan di table
    public void tampildatapesan(){
      try{
         String sql = "SELECT * FROM tbl_pesan";
         pst=connect.prepareStatement(sql);
         rs=pst.executeQuery();
         tblpesan.setModel(DbUtils.resultSetToTableModel(rs));
         
     }  catch (SQLException ex) {
            Logger.getLogger(pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    //Method tampil data ambil di table
    public void tampildataambil(){
      try{
         String sql = "SELECT * FROM tbl_ambil";
         pst=connect.prepareStatement(sql);
         rs=pst.executeQuery();
         tblambil.setModel(DbUtils.resultSetToTableModel(rs));
         
     }  catch (SQLException ex) {
            Logger.getLogger(pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    //Method ambil data dari tabel pesan
    public void ambildata(){
        try{
            String sql="select * from tbl_pesan where no_antrian='"+antrian.getText()+"'";
            pst=connect.prepareStatement(sql);
            rs=pst.executeQuery();
           if(rs.next()){
              // String data1=rs.getNString("nama");
              // nama.setText(data1);
               String data2=rs.getNString("no_telp");
               no_telp.setText(data2);
               String data3=rs.getNString("alamat");
               alamat.setText(data3);
               String data4=rs.getNString("jpewangi");
               j_pewangi.setSelectedItem(data4);
               String data5=rs.getNString("jumlah");
               jumlah.setText(data5);
               String data6=rs.getNString("harga");
               harga.setText(data6);
               String data7=rs.getNString("tanggal");
               tanggal.setText(data7);
              
           }
        } catch (SQLException ex) {
            Logger.getLogger(pembayaran.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    //Method Simpan
    private void simpan(){
        String tg=tanggal.getText();
        try{
            String sql="insert into tbl_ambil (no_antrian, nama, no_telp, alamat, j_pewangi, jumlah, harga, tanggal, total, bayar, kembali) value (?,?,?,?,?,?,?,?,?,?,?)";
            pst=connect.prepareStatement(sql);
            pst.setString(1,antrian.getText());
            pst.setString(2,nama.getText());
            pst.setString(3,no_telp.getText());
            pst.setString(4,alamat.getText());
            pst.setString(5, (String) j_pewangi.getSelectedItem());
            pst.setString(6,jumlah.getText());
            pst.setString(7,harga.getText());
            pst.setString(8,tg);
            pst.setString(9,total.getText());
            pst.setString(10,bayar.getText());
            pst.setString(11,kembalian.getText());
            
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
        } catch (SQLException ex) {
            Logger.getLogger(pelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel1 = new javax.swing.JTable();
        Report = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pewangi = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        selesai = new javax.swing.JButton();
        nama = new javax.swing.JTextField();
        no_telp = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        harga = new javax.swing.JTextField();
        tanggal = new javax.swing.JTextField();
        total = new javax.swing.JTextField();
        bayar = new javax.swing.JTextField();
        kembalian = new javax.swing.JTextField();
        antrian = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        j_pewangi = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblpesan = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblambil = new javax.swing.JTable();
        Report1 = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        tgl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        tabel1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel1);

        Report.setBackground(new java.awt.Color(0, 255, 204));
        Report.setForeground(new java.awt.Color(255, 255, 255));
        Report.setText("REPORT");
        Report.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReportMouseClicked(evt);
            }
        });
        Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(692, 694));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(692, 92));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("L(A)UNDRY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8_Shop_48px.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("AMBIL DI SINI");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 100));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel5.setText("Kembalian");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel6.setText("No Telepon");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        pewangi.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        pewangi.setText("Jenis Pewangi");
        getContentPane().add(pewangi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel9.setText("Harga");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel10.setText("Tanggal");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, -1, -1));

        jLabel11.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel11.setText("Bayar");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel12.setText("Total");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, -1, -1));

        jLabel13.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel13.setText("No.Antrian");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel14.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel14.setText("Nama");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        selesai.setBackground(new java.awt.Color(0, 255, 204));
        selesai.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 11)); // NOI18N
        selesai.setForeground(new java.awt.Color(255, 255, 255));
        selesai.setText("SELESAI");
        selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selesaiActionPerformed(evt);
            }
        });
        getContentPane().add(selesai, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 80, -1));
        getContentPane().add(nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 110, -1));
        getContentPane().add(no_telp, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 110, -1));
        getContentPane().add(alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 110, -1));
        getContentPane().add(jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 110, -1));
        getContentPane().add(harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 110, -1));
        getContentPane().add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 110, -1));
        getContentPane().add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 120, -1));

        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        getContentPane().add(bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 120, -1));
        getContentPane().add(kembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 220, 120, -1));

        antrian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                antrianKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                antrianKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                antrianKeyTyped(evt);
            }
        });
        getContentPane().add(antrian, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 110, -1));

        jLabel15.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        jLabel15.setText("Jumlah");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        j_pewangi.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 11)); // NOI18N
        j_pewangi.setForeground(new java.awt.Color(255, 255, 255));
        j_pewangi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Cair", "Bubuk" }));
        getContentPane().add(j_pewangi, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 140, 60, 20));

        tblpesan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpesan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpesanMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblpesan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 550, 110));

        tblambil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblambil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblambilMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblambil);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 550, 120));

        Report1.setBackground(new java.awt.Color(0, 255, 204));
        Report1.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 11)); // NOI18N
        Report1.setForeground(new java.awt.Color(255, 255, 255));
        Report1.setText("REPORT");
        Report1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Report1MouseClicked(evt);
            }
        });
        Report1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Report1ActionPerformed(evt);
            }
        });
        getContentPane().add(Report1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 630, 80, -1));

        kembali.setBackground(new java.awt.Color(0, 255, 204));
        kembali.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 11)); // NOI18N
        kembali.setForeground(new java.awt.Color(255, 255, 255));
        kembali.setText("KEMBALI");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });
        getContentPane().add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 630, 80, -1));

        tgl.setText("jLabel13");
        getContentPane().add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 650, 80, 30));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 11)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/20210131_142227.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selesaiActionPerformed
        int a,b;
        String h = antrian.getText();
        a = Integer.parseInt(total.getText());
        b = Integer.parseInt(bayar.getText());
        if (b < a) {
            JOptionPane.showMessageDialog(null, "Uang Anda Kurang");
        }else{
            int c = b - a;
            kembalian.setText(String.valueOf(c));
            plg.hapus(h);
            simpan();
            tampildatapesan();
            tampildataambil();
            if(Desktop.isDesktopSupported()){
                        try{
                            Desktop.getDesktop().browse(new URL("http://localhost/Laporanjava/struk.php?id="+ antrian.getText()).toURI());
                        } catch(Exception e){
                            e.printStackTrace();
                        }
                    }
                   // reset();
                    else{
                    JOptionPane.showMessageDialog(null, "gagal simpan");
                }
                }
    
            
        

    }//GEN-LAST:event_selesaiActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    private void tabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tabel1MouseClicked

    private void tblpesanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpesanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblpesanMouseClicked

    private void tblambilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblambilMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tblambilMouseClicked

    private void ReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReportMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_ReportMouseClicked

    private void ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportActionPerformed
        // TODO add your handling code here:
        if(Desktop.isDesktopSupported()){
            try{
                Desktop.getDesktop().browse(new URL("http://localhost:82/Laporanjava/laporan.php").toURI());
            } catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_ReportActionPerformed

    private void Report1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Report1MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_Report1MouseClicked

    private void Report1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Report1ActionPerformed
        // TODO add your handling code here:
        if(Desktop.isDesktopSupported()){
            try{
                Desktop.getDesktop().browse(new URL("http://localhost/Laporanjava/laporan.php").toURI());
            } catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_Report1ActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        new home().setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void antrianKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_antrianKeyPressed
    
    }//GEN-LAST:event_antrianKeyPressed

    private void antrianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_antrianKeyReleased
   
     if (!antrian.getText().equals("")) {
            try {
                st = connect.createStatement();
                rs = st.executeQuery("select * from tbl_pesan where no_antrian ='"+antrian.getText()+"'");
                if (rs.next()) {
                    nama.setText(rs.getString("nama"));
                    no_telp.setText(rs.getString("no_telp"));
                    alamat.setText(rs.getString("alamat"));
                    j_pewangi.setSelectedItem(rs.getString("jpewangi"));
                    jumlah.setText(rs.getString("jumlah"));
                    harga.setText(rs.getString("harga"));
                    tanggal.setText(rs.getString("tanggal"));
                    total.setText(rs.getString("harga"));
                }else{
                    nama.setText("");
                    no_telp.setText("");
                    alamat.setText("");
                    j_pewangi.setSelectedItem("");
                    jumlah.setText("");
                    harga.setText("");
                    tanggal.setText("");
                    total.setText("");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
    }//GEN-LAST:event_antrianKeyReleased
    }
    private void antrianKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_antrianKeyTyped
         // TODO add your handling code here:
    }//GEN-LAST:event_antrianKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Report;
    private javax.swing.JButton Report1;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField antrian;
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JComboBox<String> j_pewangi;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField no_telp;
    private javax.swing.JLabel pewangi;
    private javax.swing.JButton selesai;
    private javax.swing.JTable tabel1;
    private javax.swing.JTextField tanggal;
    private javax.swing.JTable tblambil;
    private javax.swing.JTable tblpesan;
    private javax.swing.JLabel tgl;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
